services:
  web:
    env_file:
      - ".env_template"
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:8000"
  redis:
    image: "redis:latest"
    env_file:
      - ".env_template"